### ISSUE TITLE
AWS Greengrass Discovery Support - clarifications

### ISSUE THREAD

**Issue by cy-prasanthkumar** [ARMmbed/mbed-client-for-aws#11]
**Description of defect**
We are developing a code example using the "mbed-aws-client" library for Mbed OS target, and trying to perform "Greengrass core device discovery" in the application. Could you please help us in below clarifications:

- As this library is using AWS IoT Device SDK at backend, does it also provide the APIs for Greengrass core device discovery for the application ?
- If it is not supported in the existing release, are there plans to support it in future ? It would be helpful if we can get some rough timeline.

**Target(s) affected by this defect ?**
Any Cypress target such as CY8CPROTO-062-4343W

**Toolchain(s) (name and version) displaying this defect ?**
GCC_ARM v6.3.1

**What version(s) of tools are you using. List all that apply (E.g. mbed-cli)**
mbed-cli v1.8.3

**How is this defect reproduced ?**
N/A - This is not an issue. Requested for clarification.

**Comment by andypowers** [comment]
Hi Prasanth - thanks for the comments. We haven't included support for Greengrass core device discovery as our understanding is that it requires a Linux based platform for Cortex-A type processors and requires support for containers, like Docker. 

Have we misunderstood? If so, could you provide links to any documentation on how we could incorporate this into Mbed? Thanks.

**Comment by cy-prasanthkumar** [comment]
Hi Andy,

I think we don't require Cortex-A type processor for only performing Greengrass device discovery but it is required if we are setting up the Greengrass device and registering it on AWS IoT console. Please refer to this library https://github.com/cypresssemiconductorco/aws-iot/ which supports AWS Greengrass device discovery with Mbed OS 5.15. This library doesn't support Mbed OS 6, so we preferred to take ARM's mbed-aws-client library and checking if we can do a similar device discovery.

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by cy-prasanthkumar** [comment]
Done.

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@cy-prasanthkumar it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by cy-prasanthkumar** [comment]
Closing this case as we do not have this requirement for now. We will create a new case if we are looking into AWS Greengrass  support on Mbed OS. Thanks for the support.
