### ISSUE TITLE
Clock port needs redesign

### ISSUE THREAD

**Issue by boraozgen** [ARMmbed/mbed-client-for-aws#12]
Starting and stopping threads for timer purposes does not make any sense. Threads are not supposed to be restarted according to the Mbed OS documentation. 

This was causing issues for me so I reimplemented the clock port using EventQueue. Works much smoother now, without spawning unnecessary threads. I can open a PR if you are open to contributions.

https://github.com/ARMmbed/mbed-aws-client/blob/455937ace2ddeb5078ea0c71ba51bf1b6fa67b6a/mbed/src/iot_clock.cpp#L47-L57

**Comment by ithinuel** [comment]
Thank you very much for your feedback !
We are indeed open for contribution, fell free to create a PR 👍
