### ISSUE TITLE
mbed-iot-hub-client

### ISSUE THREAD

**Issue by loverdeg** [ARMmbed/mbed-client-for-aws#5]
Any work being done to continue microsoft's existing port of their client to Mbed?

**Comment by loverdeg** [comment]
Bump

**Comment by bulislaw** [comment]
Hi guys,
sorry for not being very good in answering stuff on GitHub, busy days! Yes, we are working on making Mbed OS truly cloud neutral. We are adopting breadth first approach trying to get basic connection capabilities for number of popular cloud platforms. Later we will evaluate the more advanced features like firmware update and decide where we will spend our efforts.  So yes we are working on Azure now :)

**Comment by LDong-Arm** [comment]
Hello. Yes the idea is to continue the existing port. We'll keep you updated, thanks!

**Comment by ciarmcom** [comment]
@loverdeg thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@loverdeg it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@loverdeg it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@loverdeg it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@loverdeg it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@loverdeg it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by LDong-Arm** [comment]
Forgot to update this issue, we release an [example for Azure](https://github.com/ARMmbed/mbed-os-example-for-azure) and the [updated port for the client](https://github.com/ARMmbed/mbed-client-for-azure) a long time ago.
