### ISSUE TITLE
Network receive should handle close notify

### ISSUE THREAD

**Issue by boraozgen** [ARMmbed/mbed-client-for-aws#7]
TLSSocketWrapper returns 0 on `MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY`. This situation is not handled in `network_recv` and causes `Unexpected recv length` warning as seen in https://github.com/ARMmbed/mbed-os-example-aws/issues/9. This return value should be handled separately.

**Comment by LDong-Arm** [comment]
Hi @boraozgen, thanks for spotting the issue, I completely agree. It's conventional that a socket receive function returns 0 when the peer is closed, and we should handle that.
Please feel free to raise a PR if you have a fix already? Otherwise we can make the fix. Thanks!

**Comment by boraozgen** [comment]
Since my network port has diverged quite a lot from this repo, I unfortunately cannot open a PR for this issue. This should be easy to add though.

**Comment by ciarmcom** [comment]
@boraozgen thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@boraozgen it has been 5 days since the last reminder. Could you please update the issue header as previously requested?
