### ISSUE TITLE
Proposal: TLSSocketWrapper::set_client_cert_key() with length should be used

### ISSUE THREAD

**Issue by boraozgen** [ARMmbed/mbed-client-for-aws#9]
I propose to extend the `_IotNetworkCredentials_t` with length information for the certificate and the key, to be able to pass DER encoded credentials. `TLSSocketWrapper` has another `set_client_cert_key` method with length information, which could be called in turn from `network_new`. I can submit a PR if required.

**Comment by LDong-Arm** [comment]
Hi @boraozgen, if you already have that locally, please feel free to submit a PR and we will review it. Thanks!

**Comment by boraozgen** [comment]
Since my network port has diverged quite a lot from this repo, I unfortunately cannot open a PR for this issue.

**Comment by ciarmcom** [comment]
@boraozgen it has been 5 days since the last reminder. Could you please update the issue header as previously requested?
